site_name: 塔尖 wiki
site_url: https://wsy0655.github.io/algo-wiki/
repo_url: https://github.com/wsy0655/algo-wiki
repo_name: GitHub

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    # 不再使用 content.mathjax

nav:
  - 首页: index.md
  - 基础语法:
    - 数组:
      - 一维数组基础使用:
        - ABC344B Delimiter: 基础语法/数组/一维数组基础使用/[ABC344B] Delimiter.md
        - ABC263B Ancesto: 基础语法/数组/一维数组基础使用/[ABC263B] Ancestor.md
        - ABC228B Takahashi&#39;s Secret: 基础语法/数组/一维数组基础使用/[ABC228B] Takahashi&#39;s Secret.md
        - ABC252B Takahashi&#39;s Failure: 基础语法/数组/一维数组基础使用/[ABC252B] Takahashi&#39;s Failure.md
        - ABC265B Explore: 基础语法/数组/一维数组基础使用/[ABC265B] Explore.md
        - ABC356A Subsegment Reverse: 基础语法/数组/一维数组基础使用/[ABC356A] Subsegment Reverse.md
        - ABC241A Digit Machine: 基础语法/数组/一维数组基础使用/[ABC241A] Digit Machine.md
        - GESP202406 三级 寻找倍数: 基础语法/数组/一维数组基础使用/[GESP202406 三级] 寻找倍数.md
        - GESP202412 三级 数字替换: 基础语法/数组/一维数组基础使用/[GESP202412 三级] 数字替换.md
        - 语言月赛 202411 Phoenix: 基础语法/数组/一维数组基础使用/[语言月赛 202411] Phoenix.md
      - 一维数组计数和打标记应用:
        - ABC236B Who is missing?: 基础语法/数组/一维数组计数和打标记应用/[ABC236B] Who is missing?.md
        - ABC245B Mex: 基础语法/数组/一维数组计数和打标记应用/[ABC245B] Mex.md
        - ABC350B Dentist Aoki: 基础语法/数组/一维数组计数和打标记应用/[ABC350B] Dentist Aoki.md
        - 语言月赛 202412 题目名没活了: 基础语法/数组/一维数组计数和打标记应用/[语言月赛 202412] 题目名没活了.md
        - 语言月赛 202411 卡牌: 基础语法/数组/一维数组计数和打标记应用/[语言月赛 202411] 卡牌.md
        - 语言月赛 202411 Rise: 基础语法/数组/一维数组计数和打标记应用/[语言月赛 202411] Rise.md
        - 语言月赛 202410 同桌: 基础语法/数组/一维数组计数和打标记应用/[语言月赛 202410] 同桌.md
        - 语言月赛 202410 校门外的施工: 基础语法/数组/一维数组计数和打标记应用/[语言月赛 202410] 校门外的施工.md
        - 语言月赛 202408 于抑郁中支持: 基础语法/数组/一维数组计数和打标记应用/[语言月赛 202408] 于抑郁中支持.md
      - 二维数组基础使用:
        - 二维数组语法: 基础语法/数组/二维数组基础使用/二维数组语法.md
        - ABC254B Practical Computing: 基础语法/数组/二维数组基础使用/[ABC254B] Practical Computing.md
        - ABC356B Nutrients: 基础语法/数组/二维数组基础使用/[ABC356B] Nutrients.md
        - ABC258B Number Box: 基础语法/数组/二维数组基础使用/[ABC258B] Number Box.md
        - ABC274B Line Sensor: 基础语法/数组/二维数组基础使用/[ABC274B] Line Sensor.md
        - ABC244B Go Straight and Turn Right: 基础语法/数组/二维数组基础使用/[ABC244B] Go Straight and Turn Right.md
        - 蛇形方阵: 基础语法/数组/二维数组基础使用/蛇形方阵.md
        - 语言月赛 202408 蓝色的网易云: 基础语法/数组/二维数组基础使用/[语言月赛 202408] 蓝色的网易云.md
        - 语言月赛 202406 数组交换: 基础语法/数组/二维数组基础使用/[语言月赛 202406] 数组交换.md
      - 二维数组计数和打标记应用:
        - ABC265C Belt Conveyor: 基础语法/数组/二维数组计数和打标记应用/[ABC265C] Belt Conveyor.md
        - 语言月赛 202409 距离: 基础语法/数组/二维数组计数和打标记应用/[语言月赛 202409] 距离.md
    - 字符串:
      - 字符串基础使用:
        - 字符串语法: 基础语法/字符串/字符串基础使用/字符串语法.md
        - 语言月赛 202409 始终: 基础语法/字符串/字符串基础使用/[语言月赛 202409] 始终.md
        - 语言月赛 202408 因友情而终结: 基础语法/字符串/字符串基础使用/[语言月赛 202408] 因友情而终结.md
        - GESP202406 三级 移位: 基础语法/字符串/字符串基础使用/[GESP202406 三级] 移位.md
        - GESP202409 三级 回文拼接: 基础语法/字符串/字符串基础使用/[GESP202409 三级] 回文拼接.md
        - 语言月赛 202412 正在联系教练退赛: 基础语法/字符串/字符串基础使用/[语言月赛 202412] 正在联系教练退赛.md
        - 语言月赛 202406 通配符匹配: 基础语法/字符串/字符串基础使用/[语言月赛 202406] 通配符匹配.md
        - 语言月赛 202401 Genshin 玩家: 基础语法/字符串/字符串基础使用/[语言月赛 202401] Genshin 玩家.md
        - 语言月赛 202311 方程求解: 基础语法/字符串/字符串基础使用/[语言月赛 202311] 方程求解.md
        - ABC299C Dango: 基础语法/字符串/字符串基础使用/[ABC299C] Dango.md
        - ABC233B A Reverse: 基础语法/字符串/字符串基础使用/[ABC233B] A Reverse.md
        - ABC221B typo: 基础语法/字符串/字符串基础使用/[ABC221B] typo.md
        - ABC242B Minimize Ordering: 基础语法/字符串/字符串基础使用/[ABC242B] Minimize Ordering.md
        - ABC103B String Rotation: 基础语法/字符串/字符串基础使用/[ABC103B] String Rotation.md
        - 环状字符串: 基础语法/字符串/字符串基础使用/环状字符串.md
        - 星空: 基础语法/字符串/字符串基础使用/星空.md
      - 字符串计数问题:
        - ABC300B Same Map in the RPG World: 基础语法/字符串/字符串计数问题/[ABC300B] Same Map in the RPG World.md
        - 语言月赛 202404 非众数: 基础语法/字符串/字符串计数问题/[语言月赛 202404] 非众数.md
        - 语言月赛 202411 Enemy: 基础语法/字符串/字符串计数问题/[语言月赛 202411] Enemy.md
        - ABC248A Lacked Number: 基础语法/字符串/字符串计数问题/[ABC248A] Lacked Number.md
        - ABC249B Perfect String: 基础语法/字符串/字符串计数问题/[ABC249B] Perfect String.md
        - 字符串: 基础语法/字符串/字符串计数问题/字符串.md
  - 基础算法:
    - 复杂度: 基础算法/复杂度.md
    - 排序: 
      - 排序简介: 基础算法/排序/排序简介.md
      - 选择排序: 基础算法/排序/选择排序.md
      - 冒泡排序: 基础算法/排序/冒泡排序.md
      - 插入排序: 基础算法/排序/插入排序.md
      - 计数排序: 基础算法/排序/计数排序.md
      - STL排序: 基础算法/排序/STL排序.md
      - 结构体排序: 基础算法/排序/结构体排序.md
    - 枚举:
      - 循环枚举: 基础算法/枚举/循环枚举.md
      - 二进制枚举: 基础算法/枚举/二进制枚举.md
      - 排列枚举: 基础算法/枚举/排列枚举.md
      - 枚举优化: 基础算法/枚举/枚举优化.md
    - 递归: 基础算法/递归.md
    - 递推: 基础算法/递推.md
    - 模运算: 基础算法/模运算.md
    - 前缀和: 基础算法/前缀和.md
  - 字符串:
    - 哈希: 字符串/哈希.md
    - KMP: 字符串/KMP.md
    - Trie: 字符串/Trie.md
  - 动态规划:
    - 子序列问题: 动态规划/子序列问题.md
    - 二分优化子序列问题: 动态规划/二分优化子序列问题.md
    - 最长上升子序列方案:   动态规划/最长上升子序列方案.md
    - 最长上升子序列方案数: 动态规划/最长上升子序列方案数.md
    - 最长上升奇偶子序列: 动态规划/最长上升奇偶子序列.md
    - 最长公共子序列 LCS: 动态规划/最长公共子序列.md
    - 排列的最长公共子序列: 动态规划/排列的最长公共子序列.md
    - 最长公共子串: 动态规划/最长公共子串.md
    - 最长公共子序列方案: 动态规划/最长公共子序列方案.md
    - 反向最长公共子序列: 动态规划/反向最长公共子序列.md
    - 字母的最长公共子序列: 动态规划/字母的最长公共子序列.md
  - STL 容器: 
    - stack: STL容器/栈stack.md
    - queue: STL容器/队列queue.md
    - list: STL容器/链表list.md
    - pair和array: STL容器/pair和array.md
    - vector: STL容器/vector.md
    - iterator: STL容器/迭代器.md
    - map: STL容器/map.md
    - set: STL容器/set.md
    - bitset: STL容器/bitset.md
    - priority_queue: STL容器/priority_queue.md
  - 数据结构:
      - 单调栈: 数据结构/单调栈.md
      - 单调队列: 数据结构/单调队列.md
      - 并查集: 数据结构/并查集.md
      - 堆: 数据结构/堆.md
      - ST表与倍增: 数据结构/ST表与倍增.md
      - 树状数组: 数据结构/树状数组.md
      - 线段树:
        - 线段树基础: 数据结构/线段树/线段树基础.md
        - 线段树合并: 数据结构/线段树/线段树合并.md
        - 线段树分裂: 数据结构/线段树/线段树分裂.md
        - 线段树分治: 数据结构/线段树/线段树分治.md
  - 图论:
      - 图的相关概念: 图论/图的相关概念.md
      - 图的存储: 图论/图的存储.md
      - 图的遍历: 图论/图的遍历.md
      - 树: 图论/树.md
      - 最短路: 图论/最短路.md
      - 常见建图技巧: 图论/常见建图技巧.md
      - 最小生成树: 图论/最小生成树.md
      - 拓扑排序: 图论/拓扑排序.md
  - 数学:
    - 模运算: 数学/mod.md
    - 质数判定: 数学/质数判定.md
    - 筛法: 数学/筛法.md
    - 质因子分解: 数学/质因子分解.md
    - 最大公约数: 数学/gcd.md
    - 快速幂: 数学/快速幂.md
    - 排列组合: 数学/排列组合.md
    - 二项式定理: 数学/二项式定理.md
    - 鸽笼原理: 数学/鸽笼原理.md
    - exgcd: 数学/exgcd.md
    - 逆元: 数学/乘法逆元.md
    - 线性代数:
      - 线性代数简介: 数学/线性代数/线性代数简介.md
      - 向量: 数学/线性代数/向量.md
      - 矩阵: 数学/线性代数/矩阵.md  
      - 矩阵乘法应用: 数学/线性代数/矩阵乘法应用.md  
  - 周赛题解:
    - 语法算法周赛:
      - 语法周赛round15: 周赛/语法算法周赛/15.md
      - 语法周赛round16: 周赛/语法算法周赛/16.md
      - 语法周赛round17: 周赛/语法算法周赛/17.md
      - 语法周赛round18: 周赛/语法算法周赛/18.md
      - 语法周赛round19: 周赛/语法算法周赛/19.md
      - 算法周赛round24: 周赛/语法算法周赛/算法周赛24.md
      - 语法周赛round23: 周赛/语法算法周赛/语法周赛23.md
      - 算法周赛round25: 周赛/语法算法周赛/算法周赛25.md
      - 语法周赛round24: 周赛/语法算法周赛/语法周赛24.md
      - 算法周赛round26: 周赛/语法算法周赛/算法周赛26.md
      - 语法周赛round25: 周赛/语法算法周赛/语法周赛25.md
      - 算法周赛round27: 周赛/语法算法周赛/算法周赛27.md
      - 语法周赛round26: 周赛/语法算法周赛/语法周赛26.md
      - 算法周赛round28: 周赛/语法算法周赛/算法周赛28.md
      - 语法周赛round27: 周赛/语法算法周赛/语法周赛27.md
      - 算法周赛round29: 周赛/语法算法周赛/算法周赛29.md
      - 语法周赛round28: 周赛/语法算法周赛/语法周赛28.md
      - 算法周赛round30: 周赛/语法算法周赛/算法周赛30.md
      - 语法周赛round29: 周赛/语法算法周赛/语法周赛29.md
      - 算法周赛round31: 周赛/语法算法周赛/算法周赛31.md
      - 语法周赛round30: 周赛/语法算法周赛/语法周赛30.md
      - 算法周赛round33: 周赛/语法算法周赛/算法周赛33.md
      - 语法周赛round31: 周赛/语法算法周赛/语法周赛31.md
      - 算法周赛round34: 周赛/语法算法周赛/算法周赛34.md
    - 25强基集训测试:
      - 25暑假集训摸底测试: 周赛/25强基集训测试/摸底测试.md
      - 25暑假day1测试题解: 周赛/25强基集训测试/day1测试题解.md
      - 25暑假day2测试题解: 周赛/25强基集训测试/day2测试题解.md
      - 25暑假day3测试题解: 周赛/25强基集训测试/day3测试题解.md
      - 25暑假day4测试题解: 周赛/25强基集训测试/day4测试题解.md
      - 25暑假day5测试题解: 周赛/25强基集训测试/day5测试题解.md
      - 25暑假day6测试题解: 周赛/25强基集训测试/day6测试题解.md
      - 25暑假day7测试题解: 周赛/25强基集训测试/day7测试题解.md
      - 25暑假day8测试题解: 周赛/25强基集训测试/day8测试题解.md
      - 25暑假day10测试题解: 周赛/25强基集训测试/day10测试题解.md
    - 24强基集训测试:
      - 进阶优化思想: 周赛/24强基集训测试/进阶优化思想.md
      - 进阶贪心和二分: 周赛/24强基集训测试/进阶贪心和二分.md
      - day2测试题解: 周赛/24强基集训测试/day2测试题解.md
      - day3测试题解: 周赛/24强基集训测试/day3测试题解.md
      - day4测试题解: 周赛/24强基集训测试/day4测试题解.md
      - day5测试题解: 周赛/24强基集训测试/day5测试题解.md
      - day6测试题解: 周赛/24强基集训测试/day6测试题解.md
      - day8测试题解: 周赛/24强基集训测试/day8测试题解.md
      - day10测试题解: 周赛/24强基集训测试/day10测试题解.md
      - CSP模拟赛day1: 周赛/24强基集训测试/国庆CSP模拟赛day1.md
      - CSP模拟赛day2: 周赛/24强基集训测试/国庆CSP模拟赛day2.md
      - CSP模拟赛day3: 周赛/24强基集训测试/国庆CSP模拟赛day3.md
      - CSP模拟赛day4: 周赛/24强基集训测试/国庆CSP模拟赛day4.md
      - CSP模拟赛day5: 周赛/24强基集训测试/国庆CSP模拟赛day5.md
    - CSP模拟:
      - CSP模拟赛一: 周赛/CSP模拟赛/CSP模拟赛一.md
      - CSP模拟赛二: 周赛/CSP模拟赛/CSP模拟赛二.md
      - CSP模拟赛三: 周赛/CSP模拟赛/CSP模拟赛三.md
      - CSP模拟赛四: 周赛/CSP模拟赛/CSP模拟赛四.md
      - CSP模拟赛八: 周赛/CSP模拟赛/CSP模拟赛八.md
  - 初赛篇:
    - 进制转换与位运算: 初赛篇/进制转换与位运算.md
    - 数据结构: 初赛篇/数据结构.md
    - day1: 初赛篇/day1.md
    - day2: 初赛篇/day2.md
    - day4: 初赛篇/day4.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
      inline_syntax: dollar

# 加载官方 MathJax 脚本即可，不需要任何自定义 JS
extra_javascript:
  # 先加载你的 MathJax 配置
  - js/mathjax-config.js
  # 再加载 MathJax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 不加载 KaTeX CSS/JS
# extra_css: …
